# ETL prj manager config.yml
agency_config:
  short_name_template: "AAA-BB"
  category_id: 4
  agency_ipa_code: 'odcec_bb'
users:
  number: 3
  user1:
    name: "vsi0109"
  user2:
    name: "vsi0116"
  user3:
    name: "VM_USER"
project_config:
  git_default_branch: "main"
  gitlab:
    group_id: 126
    url: "https://gitlab-management.visura.it/"
    username: "marco.peri@visura.it"
    origin_remote_name: "etl-albosmart-stand-alone-protocol-ARC-FI"
  github:
    owner: "lupodargento"
    origin_remote_name: "FaceERAAD_codereader_v1-3"
    visibility: "private"
register_config:
  default_privacy_template:
    profileName: "privacy template default profile"
    picture: "NOT_AUTHORIZED"
    fiscalCode: "NOT_AUTHORIZED"
    vatNumber : "NOT_AUTHORIZED"
    birthDate : "NOT_AUTHORIZED"
    gender: "NOT_AUTHORIZED"
    studioAddress: "NOT_AUTHORIZED"
    studioEmail: "NOT_AUTHORIZED"
    studioPec : "NOT_AUTHORIZED"
    studioPecReginde: "NOT_AUTHORIZED"
    studioPhone: "NOT_AUTHORIZED"
    studioFax : "NOT_AUTHORIZED"
    residenceAddress: "NOT_AUTHORIZED"
    residenceEmail : "NOT_AUTHORIZED"
    residencePec: "NOT_AUTHORIZED"
    residencePecReginde: "NOT_AUTHORIZED"
    residencePhone : "NOT_AUTHORIZED"
    residenceFax: "NOT_AUTHORIZED"
    professionalDomicileAddress: "NOT_AUTHORIZED"
    professionalDomicileEmail: "NOT_AUTHORIZED"
    professionalDomicilePec : "NOT_AUTHORIZED"
    professionalDomicilePecReginde: "NOT_AUTHORIZED"
    professionalDomicilePhone   : "NOT_AUTHORIZED"
    professionalDomicileFax : "NOT_AUTHORIZED"
    taxDomicileAddress: "NOT_AUTHORIZED"
    taxDomicileEmail: "NOT_AUTHORIZED"
    taxDomicilePec : "NOT_AUTHORIZED"
    taxDomicilePecReginde: "NOT_AUTHORIZED"
    taxDomicilePhone: "NOT_AUTHORIZED"
    taxDomicileFax : "NOT_AUTHORIZED"
    mailingAddressAddress: "NOT_AUTHORIZED"
    mailingAddressEmail: "NOT_AUTHORIZED"
    mailingAddressPec : "NOT_AUTHORIZED"
    mailingAddressPecReginde: "NOT_AUTHORIZED"
    mailingAddressPhone: "NOT_AUTHORIZED"
    mailingAddressFax : "NOT_AUTHORIZED"
    studioMobilePhone : "NOT_AUTHORIZED"
    residenceMobilePhone: "NOT_AUTHORIZED"
    professionalDomicileMobilePhone: "NOT_AUTHORIZED"
    taxDomicileMobilePhone: "NOT_AUTHORIZED"
    mailingAddressMobilePhone: "NOT_AUTHORIZED"
protocol_config:
  AOO:
    number: 1
    AOO1:
      aoo1_alboclassic_aoo_id:
      aoo1_accountable_email: 'prova.email@email.it'
      aoo1_accountable_first_name: 'Mauro'
      aoo1_accountable_last_name: 'verdi'
      aoo1_accountable_phone_number: '123456'
      aoo1_date_creation: '12/04/2025'
      aoo1_name: 'nome Aoo 1'
      aoo1_unicode: 'A22HH8D'
  UO:
    number: 2
    UO1:
      uo1_alboclassic_uo_id: 1
      uo1_albosmart_uo_id:
      uo1_accountable_first_name: 'Pietro'
      uo1_accountable_second_name: 'Azzurri'
      uo1_date_creation: '19/04/2025'
      uo1_name: 'Ufficio per sessione Digitale'
      uo1_unicode: 'CGN333'
      uo1_isDefault: 'true'
    UO2:
      uo2_alboclassic_uo_id: 3
      uo2_albosmart_uo_id:
      uo2_accountable_first_name: 'Marco'
      uo2_accountable_second_name: 'Rossi'
      uo2_date_creation: '24/03/2025'
      uo2_name: 'Ufficio per sessione Cartacea'
      uo2_unicode: '888DVK'
      uo2_isDefault: 'false'
