# ETL prj manager config.yml
agency_config:
  short_name_template: "COM-GE"
  category_id: 4
  agency_ipa_code: 'odcec_ge'
users:
  number: 3
  user1:
    name: "vsi0109"
  user2:
    name: "vsi0116"
  user3:
    name: "VM_USER"
project_config:
  gitlab_group_id: 126
  gitlab_url: "https://gitlab-management.visura.it/"
  gitlab_username: "marco.peri@visura.it"
  gitlab_origin_remote_name: "etl-albosmart-stand-alone-protocol-ARC-FI"
  git_default_branch: "main"
  github_owner: "VisuraSpa"
  github_visibility: "private"
register_config:
  default_privacy_template:
    profileName: "privacy template default profile"
    picture: "NOT_AUTHORIZED"
    fiscalCode: "NOT_AUTHORIZED"
    vatNumber : "NOT_AUTHORIZED"
    birthDate : "NOT_AUTHORIZED"
    gender: "NOT_AUTHORIZED"
    studioAddress: "NOT_AUTHORIZED"
    studioEmail: "NOT_AUTHORIZED"
    studioPec : "NOT_AUTHORIZED"
    studioPecReginde: "NOT_AUTHORIZED"
    studioPhone: "NOT_AUTHORIZED"
    studioFax : "NOT_AUTHORIZED"
    residenceAddress: "NOT_AUTHORIZED"
    residenceEmail : "NOT_AUTHORIZED"
    residencePec: "NOT_AUTHORIZED"
    residencePecReginde: "NOT_AUTHORIZED"
    residencePhone : "NOT_AUTHORIZED"
    residenceFax: "NOT_AUTHORIZED"
    professionalDomicileAddress: "NOT_AUTHORIZED"
    professionalDomicileEmail: "NOT_AUTHORIZED"
    professionalDomicilePec : "NOT_AUTHORIZED"
    professionalDomicilePecReginde: "NOT_AUTHORIZED"
    professionalDomicilePhone   : "NOT_AUTHORIZED"
    professionalDomicileFax : "NOT_AUTHORIZED"
    taxDomicileAddress: "NOT_AUTHORIZED"
    taxDomicileEmail: "NOT_AUTHORIZED"
    taxDomicilePec : "NOT_AUTHORIZED"
    taxDomicilePecReginde: "NOT_AUTHORIZED"
    taxDomicilePhone: "NOT_AUTHORIZED"
    taxDomicileFax : "NOT_AUTHORIZED"
    mailingAddressAddress: "NOT_AUTHORIZED"
    mailingAddressEmail: "NOT_AUTHORIZED"
    mailingAddressPec : "NOT_AUTHORIZED"
    mailingAddressPecReginde: "NOT_AUTHORIZED"
    mailingAddressPhone: "NOT_AUTHORIZED"
    mailingAddressFax : "NOT_AUTHORIZED"
    studioMobilePhone : "NOT_AUTHORIZED"
    residenceMobilePhone: "NOT_AUTHORIZED"
    professionalDomicileMobilePhone: "NOT_AUTHORIZED"
    taxDomicileMobilePhone: "NOT_AUTHORIZED"
    mailingAddressMobilePhone: "NOT_AUTHORIZED"
protocol_config:
  AOO:
    number: 1
    AOO1:
      aoo1_alboclassic_aoo_id:
      aoo1_accountable_email: 'ordinecommercialistigenova@pec.it'
      aoo1_accountable_first_name: 'Mauro Carlo'
      aoo1_accountable_last_name: 'Rovida'
      aoo1_accountable_phone_number: '010589134'
      aoo1_date_creation: '12/04/2019'
      aoo1_name: 'Ordine dei Dottori Commercialisti e degli Esperti Contabili'
      aoo1_unicode: 'A1D778D'
  UO:
    number: 3
    UO1:
      uo1_alboclassic_uo_id: 1
      uo1_albosmart_uo_id:
      uo1_accountable_first_name: 'Mauro Carlo'
      uo1_accountable_second_name: 'Rovida'
      uo1_date_creation: '19/04/2019'
      uo1_name: 'Ufficio per la transizione al Digitale'
      uo1_unicode: 'CGNSNM'
      uo1_isDefault: 'true'
    UO2:
      uo2_alboclassic_uo_id: 3
      uo2_albosmart_uo_id:
      uo2_accountable_first_name: 'Mauro Carlo'
      uo2_accountable_second_name: 'Rovida'
      uo2_date_creation: '24/03/2021'
      uo2_name: 'OCC ORGANISMO DI COMPOSIZIONE DELLA CRISI DA SOVRAINDEBITAMENTO'
      uo2_unicode: 'IBNDVK'
      uo2_isDefault: 'false'
    UO3:
      uo3_alboclassic_uo_id: 2
      uo3_albosmart_uo_id:
      uo3_accountable_first_name: 'Luigina'
      uo3_accountable_second_name: 'Marrese'
      uo3_date_creation: '07/06/2021'
      uo3_name: 'FORMAZIONE'
      uo3_unicode: 'K99ZM9'
      uo3_isDefault: 'false'
